### ISSUE TITLE
Throwing error

### ISSUE THREAD

**Issue by amitguptagwl** [endel/js2php#25]
```
    if (parent) { node.parent = parent; }
                              ^
TypeError: Cannot set property 'parent' of null
    at visit (/usr/local/lib/node_modules/js2php/index.js:47:31)
    at visit (/usr/local/lib/node_modules/js2php/index.js:424:18)
    at visit (/usr/local/lib/node_modules/js2php/index.js:52:20)
    at visit (/usr/local/lib/node_modules/js2php/index.js:387:18)
    at visit (/usr/local/lib/node_modules/js2php/index.js:396:22)
    at visit (/usr/local/lib/node_modules/js2php/index.js:396:22)
    at visit (/usr/local/lib/node_modules/js2php/index.js:396:22)
    at visit (/usr/local/lib/node_modules/js2php/index.js:52:20)
    at visit (/usr/local/lib/node_modules/js2php/index.js:266:27)
    at visit (/usr/local/lib/node_modules/js2php/index.js:483:17)

```
Initially it was causing issue due to throw statement. But it is failing even after commenting throw statement.

Here is the javascript code [nimn.js](https://github.com/nimndata/nimnjs/blob/master/src/nimn.js). I had simplified template literals in normal string concatenation form in doubt if they are not supported.

**Comment by endel** [comment]
Hi @amitguptagwl, sorry the delay to answer. I couldn't reproduce the issue you described, though. I've successfully transpiled your [nimn.js](https://github.com/nimndata/nimnjs/blob/master/src/nimn.js) script without errors. (even though it's invalid PHP code)

**Comment by amitguptagwl** [comment]
Thanks @endel . It's nice to hear that it worked. I'm updating nimn.js . So I'll try it with new version after some days.
